<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Planificacion\Indicador;

class IndicadoresIpsSeeder extends Seeder
{
    const LETRAS = 'IPS';

    private function getPerfilId(): string
    {
        $perfil = \DB::table('planificacion.pei_profiles')
            ->where('level', 'master')
            ->where('name', 'like', '%Plan Estratégico Institucional IPS 2024%')
            ->whereNull('deleted_at')
            ->whereNull('parent_id')
            ->first();

        if (!$perfil) {
            throw new \Exception('No se encontró el perfil PEI IPS 2024. Ejecutá PeiIps2024Seeder primero.');
        }
        return $perfil->id;
    }

    public function run(): void
    {
        $ahora    = now();
        $perfilId = $this->getPerfilId();
        $this->command->info('Sembrando indicadores para: ' . $perfilId);

        $indicadores = [
            // ── Área 1: Servicios de Salud ─────────────────────────────────────────
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '001',
                'nombre'         => 'Razón de mortalidad materna institucional',
                'dimension'      => 'eficacia',
                'ambito'         => 'objetivo_estrategico',
                'descripcion'    => 'Mide el número de muertes maternas ocurridas en establecimientos de la red IPS por cada 100.000 nacidos vivos atendidos institucionalmente.',
                'variables'      => "A = Número de muertes maternas institucionales\nB = Número de nacidos vivos atendidos en establecimientos IPS",
                'formula'        => '(A / B) × 100.000',
                'unidad_medida'  => 'Razón por 100.000 NV',
                'frecuencia'     => 'anual',
                'cobertura'      => 'nacional',
                'sentido'        => 'descendente',
                'fuente'         => 'Sistema de Información Hospitalaria (SIH) — RRHH Salud IPS',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'≤ 35'],['anio'=>2026,'valor'=>'≤ 32'],['anio'=>2027,'valor'=>'≤ 30'],['anio'=>2028,'valor'=>'≤ 28']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '002',
                'nombre'         => 'Tasa de mortalidad neonatal institucional',
                'dimension'      => 'eficacia',
                'ambito'         => 'objetivo_estrategico',
                'descripcion'    => 'Mide las muertes de recién nacidos (0-28 días) ocurridas en establecimientos IPS por cada 1.000 nacidos vivos atendidos.',
                'variables'      => "A = Muertes neonatales institucionales\nB = Nacidos vivos atendidos en IPS",
                'formula'        => '(A / B) × 1.000',
                'unidad_medida'  => 'Tasa por 1.000 NV',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'descendente',
                'fuente'         => 'Sistema de Información Hospitalaria IPS',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'≤ 8'],['anio'=>2026,'valor'=>'≤ 7.5'],['anio'=>2027,'valor'=>'≤ 7'],['anio'=>2028,'valor'=>'≤ 6.5']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '003',
                'nombre'         => 'Porcentaje de redes temáticas integradas implementadas y funcionando',
                'dimension'      => 'eficacia',
                'ambito'         => 'objetivo_estrategico',
                'descripcion'    => 'Mide la proporción de redes temáticas de salud planificadas que se encuentran efectivamente implementadas y operativas en la red IPS.',
                'variables'      => "A = Redes temáticas implementadas y funcionando\nB = Total de redes temáticas planificadas",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Reportes de la Gerencia General de Salud',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'40%'],['anio'=>2026,'valor'=>'60%'],['anio'=>2027,'valor'=>'80%'],['anio'=>2028,'valor'=>'100%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '004',
                'nombre'         => 'Porcentaje de cobertura de vacunación en población objetivo',
                'dimension'      => 'eficacia',
                'ambito'         => 'objetivo_estrategico',
                'descripcion'    => 'Proporción de personas de la población objetivo que recibieron el esquema completo de vacunación en los establecimientos de la red IPS.',
                'variables'      => "A = Personas vacunadas con esquema completo\nB = Total de personas en la población objetivo",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Sistema de Información de Inmunizaciones IPS',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'85%'],['anio'=>2026,'valor'=>'88%'],['anio'=>2027,'valor'=>'90%'],['anio'=>2028,'valor'=>'92%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '005',
                'nombre'         => 'Porcentaje de programas y servicios adaptados al curso de vida',
                'dimension'      => 'calidad',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Proporción de programas y servicios de salud que incorporan el enfoque de curso de vida (infancia, adolescencia, adulto, adulto mayor) en su diseño y prestación.',
                'variables'      => "A = Programas/servicios adaptados al curso de vida\nB = Total de programas/servicios de salud vigentes",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Reportes de Gerencia General de Salud',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'30%'],['anio'=>2026,'valor'=>'50%'],['anio'=>2027,'valor'=>'70%'],['anio'=>2028,'valor'=>'85%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '006',
                'nombre'         => 'Número de investigaciones científicas aplicadas desarrolladas en establecimientos de la RIISS',
                'dimension'      => 'eficacia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Cantidad de investigaciones científicas aplicadas finalizadas y publicadas o presentadas formalmente, desarrolladas en los establecimientos de la Red Integrada de Servicios de Salud del IPS.',
                'variables'      => "A = Número de investigaciones concluidas y formalizadas",
                'formula'        => 'Conteo absoluto de A',
                'unidad_medida'  => 'Número absoluto',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Registros de la Dirección de Regulación Médica',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'4'],['anio'=>2026,'valor'=>'6'],['anio'=>2027,'valor'=>'8'],['anio'=>2028,'valor'=>'10']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '007',
                'nombre'         => 'Porcentaje de trazabilidad y abastecimiento oportuno mediante sistema informático',
                'dimension'      => 'eficiencia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Proporción de medicamentos e insumos con trazabilidad completa registrada en el sistema informático, garantizando el abastecimiento oportuno en los establecimientos.',
                'variables'      => "A = Ítems con trazabilidad completa en sistema\nB = Total de ítems gestionados",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'trimestral', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Sistema de Gestión de Suministros IPS',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'60%'],['anio'=>2026,'valor'=>'75%'],['anio'=>2027,'valor'=>'90%'],['anio'=>2028,'valor'=>'95%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '008',
                'nombre'         => 'Porcentaje de protocolos de atención y planes operativos actualizados con criterio epidemiológico',
                'dimension'      => 'calidad',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Proporción de protocolos de atención clínica y planes operativos de salud que han sido revisados y actualizados incorporando criterios epidemiológicos vigentes.',
                'variables'      => "A = Protocolos/planes actualizados con criterio epidemiológico\nB = Total de protocolos/planes vigentes",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Dirección de Regulación Médica — Registros de actualización',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'50%'],['anio'=>2026,'valor'=>'70%'],['anio'=>2027,'valor'=>'85%'],['anio'=>2028,'valor'=>'100%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '009',
                'nombre'         => 'Porcentaje de establecimientos de salud con al menos una herramienta digital implementada para la atención o gestión sanitaria',
                'dimension'      => 'eficiencia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Mide la proporción de establecimientos de la red IPS que cuentan con al menos una herramienta digital operativa para la atención clínica o la gestión administrativa sanitaria.',
                'variables'      => "A = Establecimientos con herramienta digital operativa\nB = Total de establecimientos de la red IPS",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Gerencia de Desarrollo y Tecnología — Inventario de sistemas',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'40%'],['anio'=>2026,'valor'=>'60%'],['anio'=>2027,'valor'=>'80%'],['anio'=>2028,'valor'=>'95%']],
            ],
            // ── Área 2: Prestaciones Económicas y Finanzas ────────────────────────
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '010',
                'nombre'         => 'Porcentaje de prestaciones económicas concedidas dentro del plazo establecido',
                'dimension'      => 'eficiencia',
                'ambito'         => 'objetivo_estrategico',
                'descripcion'    => 'Proporción de prestaciones económicas (jubilaciones, pensiones, subsidios) otorgadas dentro del plazo reglamentario establecido.',
                'variables'      => "A = Prestaciones concedidas dentro del plazo\nB = Total de prestaciones tramitadas",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'trimestral', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Sistema de Gestión de Prestaciones Económicas IPS',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'70%'],['anio'=>2026,'valor'=>'80%'],['anio'=>2027,'valor'=>'88%'],['anio'=>2028,'valor'=>'95%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '011',
                'nombre'         => 'Número de proyectos de reforma legal elaborados y elevados',
                'dimension'      => 'eficacia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Cantidad de proyectos de reforma normativa o legal elaborados por el IPS y formalmente elevados a las instancias competentes.',
                'variables'      => "A = Proyectos de reforma legal elaborados y elevados formalmente",
                'formula'        => 'Conteo absoluto de A',
                'unidad_medida'  => 'Número absoluto',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Gerencia de Asesoría Jurídica — Registro de proyectos',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'2'],['anio'=>2026,'valor'=>'2'],['anio'=>2027,'valor'=>'3'],['anio'=>2028,'valor'=>'3']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '012',
                'nombre'         => 'Porcentaje de consultas previsionales atendidas por canales digitales',
                'dimension'      => 'eficiencia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Proporción de consultas y trámites previsionales resueltos a través de canales digitales (portal web, app, chatbot) respecto al total de consultas atendidas.',
                'variables'      => "A = Consultas resueltas por canales digitales\nB = Total de consultas previsionales atendidas",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'trimestral', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Sistema CRM / Plataforma Digital IPS',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'20%'],['anio'=>2026,'valor'=>'35%'],['anio'=>2027,'valor'=>'50%'],['anio'=>2028,'valor'=>'65%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '013',
                'nombre'         => 'Rentabilidad real de las reservas técnicas con criterios de seguridad, liquidez y rentabilidad',
                'dimension'      => 'economia',
                'ambito'         => 'objetivo_estrategico',
                'descripcion'    => 'Mide el rendimiento real (ajustado por inflación) obtenido por las inversiones de las reservas técnicas del IPS, gestionadas bajo los criterios de seguridad, liquidez y rentabilidad.',
                'variables'      => "A = Rentabilidad nominal obtenida (%)\nB = Tasa de inflación del período (%)",
                'formula'        => 'A - B',
                'unidad_medida'  => 'Puntos porcentuales (pp)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Dirección de Inversiones — Informe de Portafolio',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'≥ 2 pp'],['anio'=>2026,'valor'=>'≥ 2.5 pp'],['anio'=>2027,'valor'=>'≥ 3 pp'],['anio'=>2028,'valor'=>'≥ 3 pp']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '014',
                'nombre'         => 'Porcentaje de inmuebles registrados y contratos fiscalizados en el Sistema de Gestión Inmobiliaria',
                'dimension'      => 'eficiencia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Proporción de inmuebles del IPS debidamente registrados y cuyos contratos han sido fiscalizados mediante el sistema de gestión inmobiliaria institucional.',
                'variables'      => "A = Inmuebles registrados con contratos fiscalizados en el sistema\nB = Total de inmuebles institucionales",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Sistema de Gestión Inmobiliaria IPS',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'50%'],['anio'=>2026,'valor'=>'70%'],['anio'=>2027,'valor'=>'85%'],['anio'=>2028,'valor'=>'100%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '015',
                'nombre'         => 'Variación porcentual de la recaudación del Aporte Obrero Patronal',
                'dimension'      => 'economia',
                'ambito'         => 'objetivo_estrategico',
                'descripcion'    => 'Mide el crecimiento o decrecimiento porcentual de la recaudación total del Aporte Obrero Patronal respecto al año anterior.',
                'variables'      => "A = Recaudación del año actual\nB = Recaudación del año anterior",
                'formula'        => '((A - B) / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Dirección de Contabilidad y Presupuesto — Reportes de recaudación',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'≥ 5%'],['anio'=>2026,'valor'=>'≥ 6%'],['anio'=>2027,'valor'=>'≥ 6%'],['anio'=>2028,'valor'=>'≥ 7%']],
            ],
            // ── Área 3: Gestión Administrativa Institucional ─────────────────────
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '016',
                'nombre'         => 'Porcentaje de avance del Plan de Trabajo MECIP implementado',
                'dimension'      => 'eficacia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Proporción de actividades del Plan de Trabajo del Modelo Estándar de Control Interno del Paraguay (MECIP) efectivamente implementadas respecto al total planificado.',
                'variables'      => "A = Actividades MECIP implementadas\nB = Total de actividades planificadas en el Plan de Trabajo MECIP",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'semestral', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Auditoría Interna IPS — Reportes MECIP',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'50%'],['anio'=>2026,'valor'=>'65%'],['anio'=>2027,'valor'=>'80%'],['anio'=>2028,'valor'=>'90%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '017',
                'nombre'         => 'Porcentaje de procesos institucionales rediseñados y documentados',
                'dimension'      => 'eficiencia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Proporción de procesos institucionales que han sido formalmente rediseñados y documentados mediante manuales o flujogramas aprobados.',
                'variables'      => "A = Procesos rediseñados y documentados\nB = Total de procesos institucionales identificados",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Dirección de Organización y Calidad (DOC)',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'25%'],['anio'=>2026,'valor'=>'45%'],['anio'=>2027,'valor'=>'65%'],['anio'=>2028,'valor'=>'85%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '018',
                'nombre'         => 'Porcentaje de establecimientos priorizados con conectividad institucional operativa',
                'dimension'      => 'eficiencia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Proporción de establecimientos de salud priorizados que cuentan con conectividad a la red institucional del IPS, operativa y con ancho de banda suficiente.',
                'variables'      => "A = Establecimientos priorizados con conectividad operativa\nB = Total de establecimientos priorizados",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'semestral', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Dirección de Tecnología de la Información y Comunicaciones (DTIC)',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'40%'],['anio'=>2026,'valor'=>'60%'],['anio'=>2027,'valor'=>'80%'],['anio'=>2028,'valor'=>'95%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '019',
                'nombre'         => 'Porcentaje de cumplimiento de controles de ciberseguridad y fortalecimiento tecnológico',
                'dimension'      => 'eficacia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Proporción de controles de ciberseguridad definidos en el plan de fortalecimiento tecnológico que se encuentran implementados y operativos.',
                'variables'      => "A = Controles de ciberseguridad implementados\nB = Total de controles definidos en el plan",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'semestral', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Dirección de TIC — Plan de Ciberseguridad',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'50%'],['anio'=>2026,'valor'=>'65%'],['anio'=>2027,'valor'=>'80%'],['anio'=>2028,'valor'=>'90%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '020',
                'nombre'         => 'Porcentaje de cargos cubiertos mediante concursos de méritos e inducción realizada',
                'dimension'      => 'calidad',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Proporción de cargos institucionales cubiertos a través de concursos de méritos, con proceso de inducción debidamente realizado.',
                'variables'      => "A = Cargos cubiertos por concurso con inducción realizada\nB = Total de cargos cubiertos en el período",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Dirección de Gestión de Talento Humano (DTH)',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'40%'],['anio'=>2026,'valor'=>'55%'],['anio'=>2027,'valor'=>'70%'],['anio'=>2028,'valor'=>'80%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '021',
                'nombre'         => 'Porcentaje de ejecución del Programa Anual de Contrataciones y simplificación de procesos',
                'dimension'      => 'eficiencia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Proporción del Programa Anual de Contrataciones (PAC) ejecutado dentro del ejercicio fiscal, con incorporación de medidas de simplificación de procesos.',
                'variables'      => "A = Contrataciones ejecutadas del PAC\nB = Total de contrataciones planificadas en el PAC",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'trimestral', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Sistema de Gestión de Contrataciones — DNCP / Registro interno',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'70%'],['anio'=>2026,'valor'=>'78%'],['anio'=>2027,'valor'=>'85%'],['anio'=>2028,'valor'=>'90%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '022',
                'nombre'         => 'Porcentaje de incremento de casos de morosidad regularizados respecto al año base 2023',
                'dimension'      => 'economia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Variación porcentual de los casos de morosidad patronal que fueron regularizados en el período respecto al total de casos de morosidad registrados en el año base 2023.',
                'variables'      => "A = Casos de morosidad regularizados en el período\nB = Casos de morosidad en el año base 2023",
                'formula'        => '((A - B) / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'linea_base_anio'=> 2023, 'linea_base_valor' => 'Año base de referencia',
                'fuente'         => 'Dirección de Contabilidad y Presupuesto — Cartera morosa',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'10%'],['anio'=>2026,'valor'=>'15%'],['anio'=>2027,'valor'=>'20%'],['anio'=>2028,'valor'=>'25%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '023',
                'nombre'         => 'Porcentaje de incremento de casos de evasión detectados respecto al año base 2023',
                'dimension'      => 'economia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Variación porcentual de los casos de evasión al seguro social detectados en el período respecto a los detectados en el año base 2023, como medida del fortalecimiento de la fiscalización.',
                'variables'      => "A = Casos de evasión detectados en el período\nB = Casos de evasión detectados en el año base 2023",
                'formula'        => '((A - B) / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'linea_base_anio'=> 2023, 'linea_base_valor' => 'Año base de referencia',
                'fuente'         => 'Dirección de Fiscalización IPS',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'15%'],['anio'=>2026,'valor'=>'20%'],['anio'=>2027,'valor'=>'25%'],['anio'=>2028,'valor'=>'30%']],
            ],
            [
                'codigo_letras'  => self::LETRAS, 'codigo_numeros' => '024',
                'nombre'         => 'Porcentaje de proyectos de infraestructura y bienes institucionales gestionados con mantenimiento y custodia documentada',
                'dimension'      => 'eficacia',
                'ambito'         => 'accion_estrategica',
                'descripcion'    => 'Proporción de proyectos de infraestructura y bienes del IPS que cuentan con plan de mantenimiento actualizado y registro documentado de custodia.',
                'variables'      => "A = Proyectos/bienes con mantenimiento y custodia documentada\nB = Total de proyectos de infraestructura y bienes institucionales",
                'formula'        => '(A / B) × 100',
                'unidad_medida'  => 'Porcentaje (%)',
                'frecuencia'     => 'anual', 'cobertura' => 'nacional', 'sentido' => 'ascendente',
                'fuente'         => 'Registro de bienes e infraestructura — Gerencia de Administración y Finanzas',
                'dependencia_responsable' => null,
                'metas'          => [['anio'=>2025,'valor'=>'40%'],['anio'=>2026,'valor'=>'60%'],['anio'=>2027,'valor'=>'80%'],['anio'=>2028,'valor'=>'90%']],
            ],
        ]; // fin array $indicadores

        // ── Inserción idempotente ─────────────────────────────────────────────
        $count = 0;
        foreach ($indicadores as $d) {
            $metas = $d['metas'] ?? [];
            unset($d['metas']);

            Indicador::firstOrCreate(
                [
                    'pei_profile_id' => $perfilId,
                    'codigo_letras'  => $d['codigo_letras'],
                    'codigo_numeros' => $d['codigo_numeros'],
                ],
                array_merge($d, [
                    'pei_profile_id' => $perfilId,
                    'metas'          => $metas,
                    'created_at'     => $ahora,
                    'updated_at'     => $ahora,
                ])
            );
            $count++;
        }

        $this->command->info("✅ {$count} indicadores IPS sembrados en el perfil " . $perfilId);
    }
}